[package]
name = "columnia"
version = "0.1.0"
description = "Estación local para preparar datos confiables"
edition = "2021"

[lib]
name = "columnia_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono = { version = "0.4.45", default-features = false }
polars = { version = "0.54.4", default-features = false, features = ["csv", "fmt"] }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.2"
